### ISSUE TITLE
Community Events

### ISSUE THREAD

**Issue by PatrickHeneise** [nodejs/community-events#1]
Let's get this repo started :)

- What would you like to see here? i.e. list of usergroups, conferences, activities, calendar, guidance on how to start a user group or how to organise a nodejs conference ...
- Who is/who wants to get involved?

/cc @nodejs/community-committee

**Comment by nebrius** [comment]
cc @RichardLitt. I remember you and I had some discussions on this topic too.

This repo is for you to use as you see fit, so I won't weight in much on the questions above. I would however recommend that, as a first step, you reach out to a few other organizers and get them to drop a few ideas in here too.

Let me know if you need help getting in touch with any other organizers

**Comment by RichardLitt** [comment]
Yup, saw this. I'm not currently organizing any Node events, so I was going to sit back for a bit and see if there was activity. 

Things I would like to see: 
- How to run a Node event (basic checklist)
- Other organizers. Let's get some human resources in here? 
- Calendar (like NodeSchool's)

**Comment by PatrickHeneise** [comment]
@dscape might sharing some LNM details?

also /cc @admataz (London) @gergelyke (Budapest) @alubbe (Berlin) @efolio (Paris) @greelgorke (Hamburg)

**Comment by admataz** [comment]
Sounds good! I'm happy to get involved and contribute and share what has worked out well and what we are still working out for LNUG. 

From a forum like this repo,  I'd also like to see  ongoing communication between organisers across the world - a couple places I think we could all benefit: 

- practical tips in setting up and keeping things running
- potential for cross promotion of events (a central calendar is a good idea)
- we've seen a lot of our organisers and members go off to live in other parts of the world - it would be good to have an up to date listing of user group meetups around the world
- related to the above - I think it would be valuable to know who are organisers in other centres and cities doing similar things. If I'm in your part of the world it may be an opportunity to meet.
- some liaison/coordination of community info with node foundation - I think as local user groups we should be well placed to encourage members to contribute, and to relay community committee
- we all ❤️ local speakers and want to encourage local developers to speak to their immediate community, but experienced speakers from out of town can be very inspiring, especially if they come with some involvement in the broader node community or have authored a well known library or module. we could establish a "travelling speakers" list - for those who want to give a local talk when they are passing though or visiting a city on business/conference/holiday
- as ever, we are trying to tackle the diversity issue - with varying degrees of success from month to month.  It would be good to know how other organisers are addressing this in their local contexts.

**Comment by dscape** [comment]
How does one use Github?

@PatrickHeneise — get in touch with Greta, but she doesn't do GitHub I think :)

Nice initiative, happy to help!

**Comment by RichardLitt** [comment]
@dscape If you want to use Google Docs or something, I'd be happy to help collect documents here. GitHub shouldn't have to be a barrier. Also, :wave:

**Comment by admataz** [comment]
interesting - github has become essential to the way we keep things running - and communication going between speakers/organisers feedback etc - I'm interested to hear that some organisers (and possibly members that we'd like to draw into some organising) may see it as a barrier... 

tip number one noted...

**Comment by PatrickHeneise** [comment]
We're also mainly running on GitHub, talk proposals etc. all go into the issue tracker. Also helps to keep recruiters away.

**Comment by dscape** [comment]
Yeah, not everyone is technical. I'm sure Greta can catch it up, but it will always be a barrier to entry in submitting talks and being involved.

By the way @PatrickHeneise our recruiters at YLD use GitHub as a platform. So.... :P
