### ISSUE TITLE
Events page from nodejs/nodejs.org being removed

### ISSUE THREAD

**Issue by bnb** [nodejs/community-events#2]
While this team hasn't solidified yet, I thought it would be nice to log that the Events page from the nodejs/nodejs.org repo has an open PR to be removed. 

The issue, as far as I know, is that it's been unmaintained. I think the community-events team would be a great team to help keep this page updated and maintained, once things get kicked off. 

Issue reference: https://github.com/nodejs/nodejs.org/pull/1314

**Comment by Trott** [comment]
From my perspective, these are the issues:

* Unmaintained. Nearly all the events listed are incorrect or misleading. 
* Map interface was a neat idea, but usability on it is poor.
* Possible false implication that most events are foundation-sponsored.
* Impossible to distinguish events in the past from events in the future in the interface. Most events are in the past, of course. Most people are interested in upcoming events, of course. So most entries are useless to users.
* ...there's actually more, but you get the idea.

I would love to see an actively curated list with a simple interface. Even better if we can get some UX testing at some point to figure out how to make it better. But if it just starts out as a short list of upcoming events with clickable links to get more info at other sites, that would be awesome. Right now, if it all it had was Node Interactive and nothing else, that would seem appropriate to me. Perhaps a list of upcoming foundation-sponsored events can be first, then below it, a list of upcoming community events not related to the foundation. Both lists should be in chronological order. The first list may warrant a sentence or three describing each entry. The second list should probably be a simple list with no descriptions. Finally, perhaps at the bottom, there could be a list of other resources for events (such as nodeschool.io website). 

For the first list, the only foundation-sponsored events that I am currently aware of are:

* Node Interactive in Vancouver Canada (October)
* The Code+Learn portion of NodeConf EU in Kilkenny Ireland (November)

Hope this helps.

**Comment by Trott** [comment]
(Oh, for the second list, you can simply update it each month based on whatever is in the newsletter the Foundation sends out each month.)
